version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    hostname: rabbitmq
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - demo-network

  frontend:
    build: ./frontend/
    container_name: frontend
    hostname: frontend
    restart: on-failure
    depends_on: [backend, rabbitmq]
    ports:
      - '3000:3000'
    networks:
      - demo-network

  backend:
    build: ./backend/
    container_name: backend
    hostname: backend
    restart: on-failure
    depends_on:
      - rabbitmq

    # Temporary exposed
    ports:
      - '8080:8080'

    networks:
      - demo-network

networks:
  demo-network:
    external: false
    ipam:
      driver: default
      config:
        - subnet: '255.255.255.250/29'
