version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbit-network

  frontend:
    build: ./frontend/
    ports:
      - '3000:3000'
    networks:
      - frontend
      - rabbit-network

  backend:
    build: ./backend/
    container_name: backend
    hostname: backend
    networks:
      - backend
      - rabbit-network

networks:
  rabbit-network: { driver: bridge } # change to host when its time for isolation
  frontend: { driver: bridge }
  backend: { driver: bridge }
